# Generated by Django 4.1.3 on 2022-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='offer',
            new_name='offers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
