# Generated by Django 4.1.3 on 2022-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
